name: Application deployment

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  buildAndDeploy:
    permissions:
      id-token: write
      contents: read
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Uses Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-west-1
      - name: "Frontend: install and build"
        run: (cd static && npm ci && npm run build)
      - name: "Frontend: run tests"
        run: (cd static && npm run test)
      - name: "Backend: install"
        run: (cd infra && npm ci)
      - name: "Backend: run infra tests"
        run: (cd infra && npm run test infrastructure)
      - name: "Backend: run application tests"
        run: (cd infra && npm run test application)
      - name: "Deploy application to AWS"
        run: (cd infra && npx cdk deploy --outputs-file ./outputs/cfnOutputs.json --require-approval never --all)
      - name: "Run e2e tests"
        run: (cd infra && npm run test End-to-end)
